services:
  selftest-web:
    container_name: selftest-web
    image: $DOCKER_USERNAME/selftest-web:$VERSION
    labels:
      # common
      - "traefik.enable=true"
      # http
      - "traefik.http.routers.selftest-web-http.entrypoints=http"
      - "traefik.http.routers.selftest-web-http.rule=Host(`$WEB_DOMAIN`)"
      #- "traefik.http.routers.selftest-web-http.middlewares=redirect-https@file"
      # https
      - "traefik.http.routers.selftest-web.entrypoints=https"
      - "traefik.http.routers.selftest-web.tls=true"
      - "traefik.http.routers.selftest-web.rule=Host(`$WEB_DOMAIN`)"
      - "traefik.http.routers.selftest-web.tls.certresolver=myresolver"
      - "traefik.http.services.selftest-web.loadbalancer.server.port=$WEB_PORT"
    networks:
      - traefik_net
    volumes:
      - "$WEB_CERT_PATH/fullchain.pem:/certs/fullchain.pem"
      - "$WEB_CERT_PATH/privkey.pem:/certs/privkey.pem"

networks:
  traefik_net:
    external: true
    name: $DEFAULT_NETWORK
