# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/apps/server"
      - "/apps/web"
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
        update-types:
          - "patch"
          - "minor"
      react:
        patterns:
          - "react"
          - "react-dom"
        update-types:
          - "patch"
          - "minor"
      eslint:
        patterns:
          - "eslint"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
    ignore:
      - dependency-name: "typescript"
        versions: ">= 5.8"
      - dependency-name: "*react*"
        versions: ">= 19"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
