services:
  server:
    image: selftest/server:latest
    container_name: server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      target: deploy
    ports:
      - 3000:3000

  web:
    image: selftest/web:latest
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: deploy
    ports:
      - 3000:3000

  db:
    image: postgres:17.2-alpine3.20
    container_name: db
    restart: always
    shm_size: 128mb
    ports:
      - "54320:5432"
    environment:
      POSTGRES_PASSWORD: example
