services:
  selftest-server:
    container_name: selftest-server
    image: $DOCKER_USERNAME/selftest-server:$VERSION
    labels:
      # common
      - "traefik.enable=true"
      # http
      - "traefik.http.routers.selftest-server-http.entrypoints=http"
      - "traefik.http.routers.selftest-server-http.rule=Host(`$SERVER_DOMAIN`)"
      - "traefik.http.routers.selftest-server-http.middlewares=redirect-https@file"
      # https
      - "traefik.http.routers.selftest-server.entrypoints=https"
      - "traefik.http.routers.selftest-server.tls=true"
      - "traefik.http.routers.selftest-server.rule=Host(`$SERVER_DOMAIN`)"
      - "traefik.http.routers.selftest-server.tls.certresolver=myresolver"
      - "traefik.http.services.selftest-server.loadbalancer.server.port=$SERVER_PORT"
    networks:
      - traefik_net
      - selftest_net
    volumes:
      - "$SERVER_CERT_PATH/fullchain.pem:/certs/fullchain.pem"
      - "$SERVER_CERT_PATH/privkey.pem:/certs/privkey.pem"

  selftest-db:
    image: postgres:17.2-alpine3.20
    container_name: selftest-db
    restart: unless-stopped
    ports:
      - "54320:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - selftest_net

volumes:
  postgres_data:

networks:
  traefik_net:
    external: true
    name: $DEFAULT_NETWORK
  selftest_net:
    driver: bridge
