name: Server CI
run-name: Server CI - ${{ github.event.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the new Docker image'
        required: true
        type: string

      latest:
        description: 'Publish the image with the latest tag'
        required: true
        type: boolean
        default: true

jobs:
  publish-image:
    runs-on: ubuntu-22.04

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Create a tag and push it
      - name: Create and push tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions-bot@users.noreply.github.com"
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/selftest-server:${{ github.event.inputs.version }} \
            -f apps/server/Dockerfile .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/selftest-server:${{ github.event.inputs.version }}

      # Optionally push the Docker image with the latest tag
      - name: Push Docker image with latest tag
        if: ${{ github.event.inputs.latest }}
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/selftest-server:${{ github.event.inputs.version }} ${{ secrets.DOCKER_USERNAME }}/selftest-server:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/selftest-server:latest
