name: Server CD

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the Docker image'
        required: true
        type: string

jobs:
  deploy-container:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate .env file
        run: |
          chmod +x ./scripts/generate-env.sh
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} VERSION=${{ github.event.inputs.version }} \
          MY_DOMAIN=${{ secrets.MY_DOMAIN }} CERT_PATH=${{ secrets.CERT_PATH }} \
          SERVER_PORT=${{ vars.SERVER_PORT }} DEFAULT_NETWORK=${{ vars.DEFAULT_NETWORK }} \
          ./scripts/generate-env.sh \
          DOCKER_USERNAME VERSION MY_DOMAIN CERT_PATH SERVER_PORT DEFAULT_NETWORK
        shell: bash

      - name: Add server to known_hosts
        run: |
          # Create the .ssh directory if it doesn't exist
          mkdir -p ~/.ssh
          # Add the server's host key to the known_hosts file
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
          echo "Host key added to known_hosts"

      - name: Add SSH private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy files to server
        run: |
          # Define server path
          SERVER_PATH="${{ secrets.SERVER_PATH }}"

          # Transfer files using rsync
          echo "Copying .env file..."
          rsync -e "ssh -o StrictHostKeyChecking=no" .env ${{ secrets.SSH_USER }}@${{ secrets.VPS_HOST }}:$SERVER_PATH/

          echo "Copying docker-compose.yml..."
          rsync -e "ssh -o StrictHostKeyChecking=no" ./apps/server/docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.VPS_HOST }}:$SERVER_PATH/

          # Run Docker Compose on the server
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.VPS_HOST }} \
            "docker compose -f $SERVER_PATH/docker-compose.yml up -d --force-recreate"
