name: Web CI
run-name: Web CI - ${{ github.event.inputs.version }}${{ github.event.inputs.dry-run == 'true' && ' (dry-run)' || '' }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the new Docker image'
        required: true

      latest:
        description: 'Publish the image with the latest tag'
        required: true
        type: choice
        default: 'true'
        options:
          - true
          - false

      dry-run:
        description: 'Dry run the workflow'
        required: true
        type: choice
        default: 'false'
        options:
          - true
          - false

      invoke-cd:
        description: 'Invoke the web CD workflow'
        required: true
        type: choice
        default: 'false'
        options:
          - true
          - false

jobs:
  publish-image:
    runs-on: ubuntu-22.04

    steps:
      # Setup initial branch default to master
      - name: Setup initial branch
        run: |
          git config --global init.defaultBranch master

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Create a tag and push it
      - name: Create and push tag
        if: ${{ github.event.inputs.dry-run != 'true' }}
        run: |
          VERSION=web-${{ github.event.inputs.version }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions-bot@users.noreply.github.com"
          git tag $VERSION
          git push origin $VERSION

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/selftest-web:${{ github.event.inputs.version }} \
            -f apps/web/Dockerfile .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        if: ${{ github.event.inputs.dry-run != 'true' }}
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/selftest-web:${{ github.event.inputs.version }}

      # Optionally push the Docker image with the latest tag
      - name: Push Docker image with latest tag
        if: ${{ github.event.inputs.latest == 'true' && github.event.inputs.dry-run != 'true' }}
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/selftest-web:${{ github.event.inputs.version }} ${{ secrets.DOCKER_USERNAME }}/selftest-web:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/selftest-web:latest

      # Optionally invoke the web CD workflow
      - name: Invoke web CD workflow
        if: ${{ github.event.inputs.invoke-cd == 'true' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: web-cd.yml
          inputs: '{ "version": "${{ github.event.inputs.version }}", "dry-run": "false" }'

      # Optionally remove the tag if any jobs fail
      - name: Remove tag if any jobs fail
        if: failure()
        run: |
          VERSION=web-${{ github.event.inputs.version }}
          git tag -d $VERSION
          git push origin --delete $VERSION
